# Generated by Django 3.2.8 on 2021-10-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcomment_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_to', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
