# Generated by Django 3.2.8 on 2021-11-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithilaStuff', '0003_auto_20211109_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='MithilaStuff/img/image.jpeg', upload_to='MithilaStuff/img'),
        ),
    ]
