# Generated by Django 3.2.8 on 2021-11-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithilaStuff', '0004_alter_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='desc',
            field=models.CharField(default='', max_length=555),
        ),
    ]
