# Generated by Django 3.2.8 on 2021-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MithilaStuff', '0005_alter_categories_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='desc',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
